[project]
name = "ror2-save-editor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MokyNZZ", email = "mokynzmc@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
ror2-save-editor = "ror2_save_editor:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
